name: Docker Build & Push to ECR
description: Builds and pushes a Docker image to AWS ECR using the commit SHA as the tag.

inputs:
  build-args:
    description: Optional Docker build arguments
    required: false
    default: ""
  image-name:
    description: Name of the ECR repository (e.g. qrify-web-dev)
    required: true
  aws-role-to-assume:
    description: IAM role ARN to assume
    required: true
  aws-region:
    description: AWS region (e.g. us-east-1)
    required: true
  ecr-registry:
    description: ECR registry URI (e.g. 1234567890.dkr.ecr.us-east-1.amazonaws.com)
    required: true

outputs:
  tag:
    description: "The Docker image tag derived from the commit SHA"
    value: ${{ steps.tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set image tag from commit SHA
      id: tag
      shell: bash
      run: echo "tag=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

    - name: Build Docker image
      shell: bash
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        TAG: ${{ steps.tag.outputs.tag }}
        BUILD_ARGS: ${{ inputs.build-args }}
      run: |
        echo "📦 Building image: $ECR_REGISTRY/${{ inputs.image-name }}:$TAG"
        docker build $BUILD_ARGS -t $ECR_REGISTRY/${{ inputs.image-name }}:$TAG .

    - name: Push Docker image
      shell: bash
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        TAG: ${{ steps.tag.outputs.tag }}
      run: |
        echo "🚀 Pushing image: $ECR_REGISTRY/${{ inputs.image-name }}:$TAG"
        docker push $ECR_REGISTRY/${{ inputs.image-name }}:$TAG
